### ISSUE TITLE
Bug: iPadOS blurry text

### ISSUE THREAD

**Issue by drmop** [lmparppei/Beat#155]
**Describe the bug**
I tried it in MacOS, the font is clear and sharp. But in iPadOS (17.5.1), there is a big problem in displaying. It seems like the font is scaled up looking very pixelated. Please refer to the screenshot comparing the status bar font and the font in the app.

**Screenshots**
![Comparison](https://github.com/user-attachments/assets/96876aa8-85f1-4bd3-bafe-38b891e4e73f)

**iPadOS version**
17.5.1

**Comment by drmop** [comment]
It would also be great if in the next release, there will be options to change font :)

**Comment by drmop** [comment]
This screenshot may be better: 
![Comparison2](https://github.com/user-attachments/assets/ba0bb537-136a-424c-bc49-f16c02a26b0a)

**Comment by lmparppei** [comment]
Oh, very weird. It's probably related to changes I did to get fonts work better on iPhones, but I can't reproduce this myself on M1 iPad Pro (11"). 

Which device are you using?

**Comment by drmop** [comment]
I'm using M4 iPad Pro (11inch)
I'm happy to provide more diagnostic information if there is a way to.

**Comment by drmop** [comment]
And also the font looks normal when it is not zoomed in.
![UnZoomed](https://github.com/user-attachments/assets/1609b246-4b4f-400d-b67c-6b506423fec4)

However as soon as start zooming it is pixelated.

**Comment by lmparppei** [comment]
I *might* have fixed this – or not. It seems like a pretty common iOS issue, which still doesn't have an agreed solution.

**Comment by lmparppei** [comment]
Version **0.1.9** is available now (or pretty soon, depending on your region) on App Store. Let me know if it fixes the issue!

**Comment by armydee** [comment]
I thought my eyesight was going, but looks like I'm not alone. I installed the app today and I have the same issue. It's odd. I'm also using a M4 iPad Pro. 11 inch.

**Comment by lmparppei** [comment]
> I thought my eyesight was going, but looks like I'm not alone. I installed the app today and I have the same issue. It's odd. I'm also using a M4 iPad Pro. 11 inch.

I *thought* this was fixed in 0.1.9 but apparently not! Could you send screenshots in both landscape and portrait format which display the pixelation?

The weirdest part is that I can't reproduce this on any other 11 inch iPad. I'll do my best to find a fix ASAP!

**Comment by lmparppei** [comment]
I think Apple has changed something related to screen scaling on M4 iPads. I added some magic to scaling code, let's see if it has any effect.

**Comment by lmparppei** [comment]
Wondering if this was fixed in later versions for M4 users?

**Comment by armydee** [comment]
> Wondering if this was fixed in later versions for M4 users?

Sorry for the delay - I have updated the app but it's still the same. It seems better than before but it still appears a bit soft. It's more obvious when viewing with "Preview" mode.

**Comment by lmparppei** [comment]
Oh, I didn't apply my fix to the preview view. But thank you for noticing that! I'll try adding some more sub-scaling for M4 iPads.
